# Generated by Django 5.2.3 on 2025-06-30 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='student',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='breaths_per_minute',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='vitals',
            name='breaths_per_minute',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='vitals',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.profile'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='temperature',
            field=models.FloatField(help_text='in °C'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='temperature',
            field=models.FloatField(help_text='in °C'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
